_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.50.2
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
bf16:
    value: true
distill:
    value: true
eval_samples_size:
    value: 150
eval_steps:
    value: 10
gradient_accumulation_steps:
    value: 8
hub_repo_id:
    value: ""
learning_rate:
    value: 0.0001
loss_fn:
    value: Pairwise
optim:
    value: paged_adamw_8bit
per_device_train_batch_size:
    value: 8
run_name:
    value: a100-20K-run
save_steps:
    value: 25
student_model:
    value: vidore/ColSmolVLM-Instruct-256M-base
teacher_model:
    value: vidore/colSmol-500M
train_samples_size:
    value: 20000
wandb_dir:
    value: colpali-distill
