teacher_model: "vidore/colqwen2-v1.0-merged" # "vidore/colqwen2-v1.0-merged" Optional vidore/colSmol-500M
student_model: "vidore/ColSmolVLM-Instruct-256M-base"
wandb_dir: "colpali-distill"
gradient_accumulation_steps: 8
per_device_train_batch_size: 4
bf16: true
learning_rate: 1.0e-4
optim: "paged_adamw_8bit"
save_steps: 100
eval_steps: 10
distill: true
train_samples_size: 20000
eval_samples_size: 150
loss_fn: "Pairwise"
hub_repo_id: "Qwen-MSE-CL-Distill"
run_name: "Qwen-MSE-CL-Distill-20k"
# resume_from_checkpoint: #Optional